# Generated by Django 5.2.8 on 2025-11-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('imagen_microbus', models.ImageField(blank=True, null=True, upload_to='microbuses/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LineaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ruta', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='routes.linea')),
            ],
            options={
                'unique_together': {('linea', 'numero_ruta')},
            },
        ),
        migrations.CreateModel(
            name='LineaPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('linea_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='routes.linearuta')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_ruta', to='routes.punto')),
            ],
            options={
                'ordering': ['linea_ruta', 'orden'],
                'unique_together': {('linea_ruta', 'orden')},
            },
        ),
    ]
